# -*- coding: utf-8 -*-
"""替换单词.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U2uUowKsfyN9v-nUMrwPGrv3xUF-3wXE
"""

# Step 1: Read the contents of the file "file_to_read.txt"
file_path = 'file_to_read.txt'

with open(file_path, 'r') as f:
    original_text = f.read()

# Step 2: Calculate the total number of occurrences of the word "terrible"
total_occurrences = original_text.lower().count("terrible")
print(f"The word 'terrible' appears {total_occurrences} times in the text.")

# Step 3: Replace every EVEN occurrence of the word "terrible" with "pathetic",
# and every ODD occurrence with "marvellous"

# Initialize variables to keep track of the current occurrence of the word "terrible"
current_occurrence = 0

# List to hold the parts of the modified text
modified_text_parts = []

# Split the original text by the word "terrible"
split_text = original_text.split("terrible")

# Loop through the split text to replace "terrible" with either "pathetic" or "marvellous"
for part in split_text[:-1]:
    current_occurrence += 1
    if current_occurrence % 2 == 0:
        modified_text_parts.append(part + "pathetic")
    else:
        modified_text_parts.append(part + "marvellous")

# Add the last part of the split text
modified_text_parts.append(split_text[-1])

# Join the modified text parts to get the full modified text
modified_text = "".join(modified_text_parts)

# Step 4: Write the modified text to a new file called "result.txt"
result_file_path = 'result.txt'
with open(result_file_path, 'w') as f:
    f.write(modified_text)

print(f"Modified text has been written to {result_file_path}.")